version: '3.8'

services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: content_app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  sender_service:
    build:
      context: .
      dockerfile: apps/sender_service/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - rabbitmq

  consumer_service:
    build:
      context: .
      dockerfile: apps/consumer_service/Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      - rabbitmq

volumes:
  pgdata:
